name = "images"
main = "src/worker.ts"
compatibility_date = "2023-07-17"

[vars]
IMAGE_PREFIX_URL = "https://image.nosharp.cc"

[[r2_buckets]]
binding = 'IMAGE_BUCKET' # <~ valid JavaScript variable name
bucket_name = 'screenshots'
